name: json_preferences
description: Combine json object with [SharedPreferences]. And an extended version with notifier.
version: 0.2.0
homepage: https://github.com/J-Siu/json_preferences

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lazy_collection: ^0.1.1
  shared_preferences: ^2.0.15

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
